import { HTTP_METHOD } from '../../http/constants.js'
import type { Route } from '../../http/router.js'
import { SOCIAL_ROUTES } from './constants/social.constants.js'
import {
  acceptFriendController,
  blockFriendController,
  createChatController,
  createChatMessageController,
  createCommunityController,
  createCommunityPostController,
  createMemoryCommentController,
  feedController,
  followUserController,
  joinCommunityController,
  leaveCommunityController,
  listChatMessagesController,
  listCommunitiesController,
  listCommunityPostsController,
  listMemoryCommentsController,
  loginController,
  panelController,
  reactCommentController,
  registerController,
  requestFriendController,
  silenceChatController,
} from './controllers/social.controller.js'
import { withSocialErrors } from './middlewares/social.middleware.js'

export const socialRoutes: readonly Route[] = [
  { method: HTTP_METHOD.POST, path: SOCIAL_ROUTES.REGISTER, handler: withSocialErrors(registerController) },
  { method: HTTP_METHOD.POST, path: SOCIAL_ROUTES.LOGIN, handler: withSocialErrors(loginController) },
  { method: HTTP_METHOD.GET, path: SOCIAL_ROUTES.PANEL, handler: withSocialErrors(panelController) },
  { method: HTTP_METHOD.GET, path: SOCIAL_ROUTES.COMMUNITIES, handler: withSocialErrors(listCommunitiesController) },
  { method: HTTP_METHOD.GET, path: SOCIAL_ROUTES.LEGACY_COMMUNITIES, handler: withSocialErrors(listCommunitiesController) },
  { method: HTTP_METHOD.POST, path: SOCIAL_ROUTES.COMMUNITIES, handler: withSocialErrors(createCommunityController) },
  { method: HTTP_METHOD.POST, path: SOCIAL_ROUTES.LEGACY_COMMUNITIES, handler: withSocialErrors(createCommunityController) },
  { method: HTTP_METHOD.POST, path: SOCIAL_ROUTES.COMMUNITY_JOIN, handler: withSocialErrors(joinCommunityController) },
  { method: HTTP_METHOD.POST, path: SOCIAL_ROUTES.LEGACY_COMMUNITY_JOIN, handler: withSocialErrors(joinCommunityController) },
  { method: HTTP_METHOD.POST, path: SOCIAL_ROUTES.COMMUNITY_LEAVE, handler: withSocialErrors(leaveCommunityController) },
  { method: HTTP_METHOD.POST, path: SOCIAL_ROUTES.LEGACY_COMMUNITY_LEAVE, handler: withSocialErrors(leaveCommunityController) },
  { method: HTTP_METHOD.GET, path: SOCIAL_ROUTES.COMMUNITY_POSTS, handler: withSocialErrors(listCommunityPostsController) },
  { method: HTTP_METHOD.GET, path: SOCIAL_ROUTES.LEGACY_COMMUNITY_POSTS, handler: withSocialErrors(listCommunityPostsController) },
  { method: HTTP_METHOD.POST, path: SOCIAL_ROUTES.COMMUNITY_POSTS, handler: withSocialErrors(createCommunityPostController) },
  { method: HTTP_METHOD.POST, path: SOCIAL_ROUTES.LEGACY_COMMUNITY_POSTS, handler: withSocialErrors(createCommunityPostController) },
  { method: HTTP_METHOD.GET, path: SOCIAL_ROUTES.FEED, handler: withSocialErrors(feedController) },
  { method: HTTP_METHOD.GET, path: SOCIAL_ROUTES.MEMORY_COMMENTS, handler: withSocialErrors(listMemoryCommentsController) },
  { method: HTTP_METHOD.POST, path: SOCIAL_ROUTES.MEMORY_COMMENTS, handler: withSocialErrors(createMemoryCommentController) },
  { method: HTTP_METHOD.POST, path: SOCIAL_ROUTES.COMMENT_REACTION, handler: withSocialErrors(reactCommentController) },
  { method: HTTP_METHOD.POST, path: SOCIAL_ROUTES.FRIEND_REQUEST, handler: withSocialErrors(requestFriendController) },
  { method: HTTP_METHOD.POST, path: SOCIAL_ROUTES.FRIEND_ACCEPT, handler: withSocialErrors(acceptFriendController) },
  { method: HTTP_METHOD.POST, path: SOCIAL_ROUTES.FRIEND_BLOCK, handler: withSocialErrors(blockFriendController) },
  { method: HTTP_METHOD.POST, path: SOCIAL_ROUTES.USER_FOLLOW, handler: withSocialErrors(followUserController) },
  { method: HTTP_METHOD.POST, path: SOCIAL_ROUTES.CHATS, handler: withSocialErrors(createChatController) },
  { method: HTTP_METHOD.GET, path: SOCIAL_ROUTES.CHAT_MESSAGES, handler: withSocialErrors(listChatMessagesController) },
  { method: HTTP_METHOD.POST, path: SOCIAL_ROUTES.CHAT_MESSAGES, handler: withSocialErrors(createChatMessageController) },
  { method: HTTP_METHOD.POST, path: SOCIAL_ROUTES.CHAT_SILENCE, handler: withSocialErrors(silenceChatController) },
]
