export const SOCIAL_TABLES = {
  USERS: 'users',
  SESSIONS: 'sessions',
  TICKETS: 'tickets',
  ORDERS: 'orders',
  MEMORY_COMMENTS: 'memory_comments',
  COMMENT_REACTIONS: 'comment_reactions',
  COMMUNITIES: 'communities',
  COMMUNITY_MEMBERS: 'community_members',
  COMMUNITY_FOLLOWS: 'community_follows',
  POSTS: 'posts',
  POST_REACTIONS: 'post_reactions',
  NOTIFICATIONS: 'notifications',
  FRIENDSHIPS: 'friendships',
  USER_FOLLOWS: 'user_follows',
  CHATS: 'chats',
  CHAT_MEMBERS: 'chat_members',
  CHAT_MESSAGES: 'chat_messages',
} as const

export const SOCIAL_ROUTES = {
  REGISTER: '/api/users/register',
  LOGIN: '/api/users/login',
  PANEL: '/api/me/panel',
  PROFILE: '/api/parcero/:alias',
  MEMORY_COMMENTS: '/api/memories/:id/comments',
  COMMENT_REACTION: '/api/comments/:id/reactions',
  COMMUNITIES: '/api/communities',
  COMMUNITY_JOIN: '/api/communities/:id/join',
  COMMUNITY_LEAVE: '/api/communities/:id/leave',
  COMMUNITY_FOLLOW: '/api/communities/:id/follow',
  COMMUNITY_POSTS: '/api/communities/:id/posts',
  LEGACY_COMMUNITIES: '/api/comunidades',
  LEGACY_COMMUNITY_JOIN: '/api/comunidades/:id/join',
  LEGACY_COMMUNITY_LEAVE: '/api/comunidades/:id/leave',
  LEGACY_COMMUNITY_FOLLOW: '/api/comunidades/:id/follow',
  LEGACY_COMMUNITY_POSTS: '/api/comunidades/:id/posts',
  POST_REACTIONS: '/api/posts/:id/reactions',
  FEED: '/api/feed',
  FRIEND_REQUEST: '/api/friends/request',
  FRIEND_ACCEPT: '/api/friends/:id/accept',
  FRIEND_BLOCK: '/api/friends/:id/block',
  USER_FOLLOW: '/api/users/:id/follow',
  CHATS: '/api/chats',
  CHAT_MESSAGES: '/api/chats/:id/messages',
  CHAT_SILENCE: '/api/operar/chats/:id/silence',
} as const

export const SOCIAL_MESSAGES = {
  PRIVACY_REQUIRED: 'Necesitas leer el aviso de privacidad para continuar.',
} as const
