export const HOME_JOIN_LABEL = 'Grupo de WhatsApp'

export const HOME_PULSE_COPY = {
  heading: 'El parche',
  lead: 'Lo más reciente. Si algo urge, el grupo de WhatsApp.',
  empty: 'Aún no hay publicaciones.',
  cta: 'Ver más',
} as const

export const HOME_BOARD_COPY = {
  kicker: 'por el parche',
  tagline: 'La próxima rodada, los kilómetros y un recorte de Paola.',
  splashPhrase: 'Nuestra voz importa',
  motto: 'No importa el CC · Aprendamos · Compartamos · Seguridad en la vía',
  scrollLabel: 'Ver más',
  panelLabel: 'Hoy',
  panelKmLabel: 'Kilómetros',
  panelPaolaLabel: 'Paola',
  panelMemoryCaption: 'Ruta',
  panelEmptyMedia: 'Aún no hay foto.',
  panelTitle: 'Rodada Anapoima :)',
  splashSoon: 'Pronto',
  nextCta: 'Parchese aquí',
  parcheseCta: 'Parchese',
  kmHeading: 'Kilómetros',
  kmLabel: 'Lo que hemos rodado',
  memoryHeading: 'Memoria',
  voiceHeading: 'Tu voz',
  voiceCta: 'Tips de vía',
  officialCta: 'Consulta oficial',
  paolaHeading: 'Paola',
  paolaCite: 'Paola',
  paolaCta: 'Conocer a Paola',
  stamp: '¡Nos vemos en la ruta!',
  kpiRodadas: 'rodadas',
  kpiKm: 'km acumulados',
  kpiIntegrantes: 'integrantes',
  channelWa: 'El grupo del día a día.',
  channelWeb: 'Las rodadas, el cupo y la tienda.',
} as const
