export const SESSION_STORAGE_KEY = 'paola_session_id'
export const ALIAS_STORAGE_KEY = 'paola_alias'

export const CUENTA_COPY = {
  title: 'Cuenta',
  lead: 'El sitio se mira sin login. La cuenta es para cupo a tu nombre, pedido y el canal web. WhatsApp no se apaga.',
  register: 'Registro',
  login: 'Entrar',
  panel: 'Panel',
  logout: 'Salir',
  tickets: 'Tickets',
  ticketsEmptyTitle: 'Sin tickets',
  ticketsEmpty: 'Cuando te apuntes con esta cuenta, el cupo aparece aquí.',
  orders: 'Pedidos',
  ordersEmptyTitle: 'Sin pedidos',
  ordersEmpty: 'El lavado y lo de Tienda quedan a tu nombre cuando hay cuenta.',
  notices: 'Avisos',
  noticesEmpty: 'No tienes avisos nuevos.',
  membership: 'Membresía paga: Paola aún no definió precio ni beneficios. No se cobra a ciegas.',
  feed: 'Feed',
  friends: 'Amigos',
  friendsLead: 'Amigos en la web. El número de WhatsApp no se muestra.',
  friendsEmpty: 'Todavía no tienes amigos vinculados en la web.',
  pending: 'Solicitudes',
  pendingEmpty: 'Nadie te ha enviado una solicitud.',
  outgoing: 'Enviadas',
  accept: 'Aceptar',
  block: 'Bloquear',
  request: 'Agregar amigo',
  aliasPlaceholder: 'Alias del parcero',
  chat: 'Chat web',
  chatLead: 'Canal web, paralelo a WhatsApp. Emergencias: líneas oficiales.',
  chatEmpty: 'Sin hilos. Escribe a un amigo para abrir uno.',
  chatSend: 'Enviar',
  chatOpen: 'Abrir chat',
  outingThread: 'Hilo de la rodada',
  photoFallback: 'Foto',
  voiceFallback: 'Nota de voz',
  photoUrl: 'Foto (enlace)',
  voiceUrl: 'Nota de voz (enlace de audio)',
  visibility: 'Perfil público',
  visibilityLead: 'Alias, moto y km opcionales. Nunca WhatsApp ni correo.',
  visibilityCta: 'Aparecer como parcero',
  visibilityOff: 'Ocultar perfil',
  failRegister: 'No se pudo registrar.',
  failLogin: 'No se pudo entrar.',
  failGeneric: 'No se pudo completar.',
} as const

export const PARCERO_COPY = {
  title: 'Parcero',
  lead: 'Ficha pública. Integrante del club no es lo mismo que esta cuenta. Nunca se muestra WhatsApp ni correo.',
  hidden: 'Ese alias no aparece en público, o no hay consentimiento.',
  km: 'Km (si los contamos)',
  moto: 'Moto',
  follow: 'Seguir',
  friend: 'Agregar amigo',
  memberNote: 'Si también sale en Así va el parche, es porque Paola publicó consentimiento de integrante. Esta ficha es otra cosa.',
} as const

export const OPERAR_REPORTS_COPY = {
  heading: 'Cola de denuncias',
  lead: 'Publica, oculta o rechaza sin pegar el ID. Es un reporte del parche, no un proceso legal.',
  empty: 'No hay denuncias en cola.',
  publish: 'Publicar',
  hide: 'Ocultar',
  reject: 'Rechazar',
  note: 'Nota (opcional)',
  fail: 'No se pudo moderar denuncia.',
  ok: 'Denuncia moderada.',
} as const
