export const SESSION_STORAGE_KEY = 'paola_session_id'
export const ALIAS_STORAGE_KEY = 'paola_alias'

export const CUENTA_COPY = {
  title: 'Cuenta',
  kicker: 'Paola Biker',
  lead: 'No necesitas cuenta para mirar el sitio. Ábrela si quieres un cupo o un pedido a tu nombre.',
  register: 'Registro',
  registerCta: 'Crear cuenta',
  login: 'Entrar',
  loginCta: 'Entrar',
  panel: 'Panel',
  logout: 'Salir',
  emailLabel: 'Correo',
  aliasLabel: 'Alias',
  passwordLabel: 'Clave',
  messageLabel: 'Mensaje',
  tickets: 'Tickets',
  ticketsEmptyTitle: 'Sin tickets',
  ticketsEmpty: 'Cuando te anotes a una rodada, el cupo queda aquí.',
  orders: 'Pedidos',
  ordersEmptyTitle: 'Sin pedidos',
  ordersEmpty: 'Los pedidos de tienda y lavado quedan aquí cuando uses tu cuenta.',
  notices: 'Avisos',
  noticesEmpty: 'No tienes avisos nuevos.',
  membership: 'Membresía paga: precio y beneficios en definición. No se cobra a ciegas.',
  feed: 'Feed',
  friends: 'Amigos',
  friendsLead: 'Tus amigos del parche. El número de WhatsApp no se muestra.',
  friendsEmpty: 'Todavía no tienes amigos agregados.',
  pending: 'Solicitudes',
  pendingEmpty: 'Nadie te ha enviado una solicitud.',
  outgoing: 'Enviadas',
  accept: 'Aceptar',
  block: 'Bloquear',
  request: 'Agregar amigo',
  aliasPlaceholder: 'Alias del parcero',
  chat: 'Chat web',
  chatLead: 'Puedes escribirte por aquí. Si es una emergencia, llama a las líneas oficiales.',
  chatEmpty: 'Aún no hay conversaciones.',
  chatSend: 'Enviar',
  chatOpen: 'Abrir chat',
  outingThread: 'Hilo de la rodada',
  photoFallback: 'Foto',
  voiceFallback: 'Nota de voz',
  photoUrl: 'Foto (enlace)',
  voiceUrl: 'Nota de voz (enlace de audio)',
  visibility: 'Perfil público',
  visibilityLead: 'Puedes mostrar alias, moto y kilómetros. Nunca WhatsApp ni correo.',
  visibilityCta: 'Aparecer como parcero',
  visibilityOff: 'Ocultar perfil',
  failRegister: 'No se pudo registrar.',
  failLogin: 'No se pudo entrar.',
  failGeneric: 'No se pudo completar.',
} as const

export const PARCERO_COPY = {
  title: 'Parcero',
  lead: 'Perfil público. No se muestra WhatsApp ni correo.',
  hidden: 'Este perfil no está visible, o no hay permiso para mostrarlo.',
  km: 'Km (si los contamos)',
  moto: 'Moto',
  follow: 'Seguir',
  friend: 'Agregar amigo',
  memberNote: 'Si también aparece en Así va el parche, es con su permiso.',
  followNeedAccount: 'Entra a tu cuenta para seguir.',
  followed: 'Ahora lo sigues.',
  friendNeedAccount: 'Entra a tu cuenta para agregar amigo.',
  friendSent: 'Solicitud enviada.',
} as const

export const OPERAR_REPORTS_COPY = {
  heading: 'Cola de denuncias',
  lead: 'Publica, oculta o rechaza sin pegar el ID. Es un reporte del parche, no un proceso legal.',
  empty: 'No hay denuncias en cola.',
  publish: 'Publicar',
  hide: 'Ocultar',
  reject: 'Rechazar',
  note: 'Nota (opcional)',
  fail: 'No se pudo moderar denuncia.',
  ok: 'Denuncia moderada.',
} as const
