export const SOCIAL_COPY = {
  activityTab: 'Actividad',
  activityHeading: 'Actividad del parche',
  activityLead: 'Lo más reciente. Si destacamos algo, sale de primeras.',
  activityEmptyTitle: 'Aún no hay actividad',
  activityEmpty: 'Aún no hay actividad.',
  activityOuting: 'Salida',
  activityMemory: 'Memoria',
  activityPost: 'Post',
  activityHighlighted: 'Destacado',
  feedLink: 'Ver el feed',
  outingThread: 'Hilo de la rodada',
  outingThreadLead: 'Chat de esta salida, para quien tiene cupo. El grupo de WhatsApp sigue abierto.',
  outingThreadEmpty: 'Aún no hay mensajes en este hilo.',
  outingThreadForbidden: 'Este hilo es para quien tiene el cupo a su nombre.',
  outingReadOnly: 'La salida está cerrada o ya se rodó. El hilo es solo lectura.',
  outingSend: 'Enviar al hilo',
  photoUrl: 'Foto (enlace)',
  voiceUrl: 'Nota de voz (enlace de audio)',
  hide: 'Ocultar',
  pin: 'Fijar',
  reply: 'Responder',
  replyPlaceholder: 'Respuesta',
  photoFallback: 'Foto del parche',
  pinOuting: 'Fijar aviso en hilo',
  pinOutingLead: 'Aviso fijado. Queda arriba en el chat de esa salida.',
  pinOutingOk: 'Aviso fijado en el hilo.',
  highlight: 'Destacar',
  highlightLead: 'El post destacado sale primero en Actividad de Parchese.',
  highlightOk: 'Post actualizado.',
  moderator: 'Moderador delegado',
  moderatorLead: 'Solo quien modera nombra o revoca ese rol. Oculta o fija posts de ESA comunidad. No toca denuncias de Tu voz ni banea global.',
  moderatorAlias: 'Alias',
  moderatorCommunity: 'Comunidad',
  moderatorName: 'Nombrar moderador',
  moderatorRevoke: 'Revocar',
  moderatorOk: 'Rol actualizado.',
  postPhotos: 'Fotos (enlaces, uno por línea, máx. 6)',
} as const
